version: "3.8"

services:
  site:
    image: node:14
    ports:
      - 3000:3000
    working_dir: /home/node/app
    user: "1000"
    command: /bin/sh -c "yarn && yarn dev"
    volumes:
      - ./:/home/node/app
    environment:
      DISCORD_CLIENT_ID: ~
      DISCORD_CLIENT_SECRET: ~
      SHINOA_API_URL: http://host.docker.internal:8080
    tty: false

  apollo_codegen:
    image: node:14
    user: node
    working_dir: /home/node/app
    command: bash -c "yarn run apollo client:codegen --target=typescript --watch"
    volumes:
      - ./:/home/node/app
